### PR TITLE
Update websocket.md

### PR DESCRIPTION
**Pull request by htfc786**
给websocket章节增加了一个提示

### CODE REVIEW

**Review by maslow — APPROVED** [review]

**Comment by maslow** [comment]
> [CLA assistant check](https://cla-assistant.io/labring/laf?pullRequest=407) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/labring/laf?pullRequest=407) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/labring/laf?pullRequest=407) it.</sub>

Hi 感谢 PR，你还需要把这个签一下才能合并

**Comment by htfc786** [comment]
我想问一下，这个怎么签啊？
Screenshot_20221114_193812_com android chrome

**Comment by htfc786** [comment]
您好，我不会签这个呀，这个应该不会有什么法律吧。。。我未成年人不想留下案底

**Comment by htfc786** [comment]
感谢感谢，这样就好了哈
Screenshot_20221114_195626_com android chrome

**Pull request merged**
