### PR TITLE
feat(web): add the pointer style for CopyText

### PR DESCRIPTION
**Pull request by imyuanx**
image

### CODE REVIEW

**Comment by 0fatal** [comment]
add "cursor-pointer" to the icon, don't add to CopyText directly

**Review by 0fatal — CHANGES_REQUESTED** [review]
add "cursor-pointer" to the icon, don't add to CopyText directly

**Comment by imyuanx** [comment]
> add "cursor-pointer" to the icon, don't add to CopyText directly

I don't think we just to add `cursor-pointer` to icon, because the entire `CopyText` is clickable.

If we just add `cursor-pointer` to the icon then customize children of `<CopyText />`, you can see that, It's not user-friendly.

image

**Comment by 0fatal** [comment]
> > add "cursor-pointer" to the icon, don't add to CopyText directly
> 
> I don't think we just to add `cursor-pointer` to icon, because the entire `CopyText` is clickable.
> 
> If we just add `cursor-pointer` to the icon then customize children of `<CopyText />`, you can see that, It's not user-friendly.
> 
> image

Trying to keep components single duty and not doing too many things. Also, have you tested all the places where CopyText is used?

**Comment by imyuanx** [comment]
Hello, there are some changes here and I tested almost all of the `CopyText`, I removes `cursor-pointer` from the all `CopyText` classname.

**Review by 0fatal — APPROVED** [review]

**Pull request merged**
